esphome:
  name: esp-mom-bedroom

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "3a5bf2861b45733b2c9b0ceab7c1ced1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Mom-Bedroom Fallback Hotspot"
    password: "1mmh5jrxEQLU"

captive_portal:
    

output:
  - platform: gpio
    id: "esp_relay_one"
    pin: D5
    inverted: true
    
  - platform: gpio
    id: "esp_relay_two"
    pin: D6
    inverted: true
    
  - platform: gpio
    id: "esp_relay_three"
    pin: D7
    inverted: true
    
  - platform: gpio
    id: "esp_relay_four"
    pin: D8   
    inverted: true

 # - platform: gpio
 #   id: "esp_indicator_one"
 #   pin: D4   
 #   inverted: true     

sensor:    
  - platform: dht
    pin: D1
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 15s
    model: DHT11
     
light:
  - platform: binary
    output: "esp_relay_one"
    name: "Mom Bedroom Light 1"          
    
  - platform: binary
    output: "esp_relay_two"
    name: "Mom Bedroom Light 2"  

  - platform: binary
    output: "esp_relay_three"
    name: "Mom Bedroom Fan"          
    
  - platform: binary
    output: "esp_relay_four"
    name: "Mom Bedroom Table Lamp"  
    
  #- platform: binary
  #  output: "esp_indicator_one"
  #  name: "Mom Bedroom ESP Indicator"      
        
