esphome:
  name: esp-computer-room

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "5efa9a1ae8e70d28e638682b88b995f2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Computer-Room"
    password: "asm5W3uOcAVc"

captive_portal:

output:
 # - platform: gpio
 #   id: "esp_indicator_one"
 #   pin: D4   
 #   inverted: true 
 
  - platform: gpio
    id: "esp_relay_one"
    pin: D5
    inverted: true
    
  - platform: gpio
    id: "esp_relay_two"
    pin: D6
    inverted: true
    
  - platform: gpio
    id: "esp_relay_three"
    pin: D7
    inverted: true
    
  - platform: gpio
    id: "esp_relay_four"
    pin: D8   
    inverted: true
    
     
light:
  #- platform: binary
  #  output: "esp_indicator_one"
  #  name: "Mom Bedroom ESP Indicator"   

  - platform: binary
    output: "esp_relay_one"
    name: "Computer TubeLight"          
    
  - platform: binary
    output: "esp_relay_two"
    name: "Computer Night Light"  

  - platform: binary
    output: "esp_relay_three"
    name: "Focus Light"          

  - platform: binary
    output: "esp_relay_four"
    name: "Monitor Socket"  
     
